### ISSUE TITLE
Geek Mental Help 2015

### ISSUE THREAD

**Issue by mikebell** [malarkey/geek-mental-help-week#46]
Hi

Is anything happening this year. Me and a friend are organising an evening where on the 28th and was wondering if anyone else was or whether it's even being run this year.

**Comment by psdesignuk** [comment]
I believe Andy Clarke was planning something and contacted me about it but nothing happened past the initial conversation?

**Comment by Heydon** [comment]
I just passed the repository over to Andy. He's running a bit late, I think, but he's on it!

**Comment by mikebell** [comment]
If you need a hand with anything let me know.

**Comment by Heydon** [comment]
Thanks!

**Comment by seriema** [comment]
Should there be a 2015 folder with an `index.html` to get things started at least?

**Comment by mikebell** [comment]
@seriema The main index.html has been updated to reflect 2015. Just need @malarkey to review and merge in the new PRs to start getting more content on there.

**Comment by mikebell** [comment]
Closing since it's all updated now and PRs are flowing in.
