### ISSUE TITLE
Any quizes/adult game suggestions?

### ISSUE THREAD

**Issue by sunscreem** [malarkey/geek-mental-help-week#79]
We've got our regular PHP next week so we are theming it around mental health.

I was thinking of giving the group some kind of pub-quiz or other 'game' that's a little less heavy than a talk. 

Its a random 'issue' but I thought I post here asking if anyone has done this or knows of any resources?

**Comment by malarkey** [comment]
You know what? I don’t. Sorry. That would be a terrific thing to do. If it’s mental health themed event, don’t forget to add it to the website!
